name: Nightly Beta Deployment

on:
    workflow_dispatch:
    schedule:
        - cron: '0 3 * * *'  # Every day at 03:00 UTC

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Beta Environment
        id: deploy
        continue-on-error: true
        run: |
          cd site

          # Deploy preview service for that user
          gcloud run deploy beta-preview \
            --source . \
            --region us-east4 \
            --platform managed \
            --allow-unauthenticated
